create table preguntas(

id bigint generated by default as identity,
titulo varchar(100) not null,
mensaje text not null,
fecha_creacion timestamp not null,
status varchar(20) not null,
autor_id bigint not null,
curso_id bigint not null,
activo boolean not null,


primary key(id),
constraint uk_preguntas_mensaje
unique(mensaje),

constraint fk_preguntas_autor
foreign key(autor_id)
references usuarios(id),

constraint fk_preguntas_curso
foreign key(curso_id)
references cursos(id)
);
