create table respuestas(

id bigint generated by default as identity,
mensaje text not null,
pregunta_id bigint not null,
fecha_creacion timestamp not null,
autor_id bigint not null,
solucion boolean not null,
activo boolean not null,

primary key(id),

constraint fk_respuestas_pregunta
foreign key(pregunta_id)
references preguntas(id),

constraint fk_respuestas_autor
foreign key(autor_id)
references usuarios(id)

);