create table respuestas(

id bigint generated by default as identity,
mensaje text not null,
topico_id bigint not null,
fecha_creacion timestamp not null,
autor_id bigint not null,
solucion boolean not null,

primary key(id),

constraint fk_respuestas_topico
foreign key(topico_id)
references topicos(id),

constraint fk_respuestas_autor
foreign key(autor_id)
references usuarios(id)

);